name: Build VPN Clients (Win32 + x64)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt 5.15.2
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: win32_msvc2019

      - name: Install Qt 5.15.2 x64
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: win64_msvc2019_64

      # --- Ставим MSBuild ---
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Check MSBuild
        run: where msbuild

      # --- Качаем QtMsBuild ---
      - name: Download QtMsBuild
        run: git clone --depth=1 https://github.com/qt-labs/vstools.git vstools_src

      # --- Собираем QtMsBuild ---
      - name: Build QtMsBuild
        run: |
          msbuild vstools_src\QtMSBuild\QtMSBuild.csproj /p:Configuration=Release
          mkdir "$env:Qt5_Dir\msbuild"
          Copy-Item "vstools_src\QtMSBuild\bin\Release\*" "$env:Qt5_Dir\msbuild\" -Recurse -Force

          echo "=== Проверяем, что Qt.props есть ==="
          dir "$env:Qt5_Dir\msbuild"
          Get-Content "$env:Qt5_Dir\msbuild\Qt.props" -TotalCount 20

      # --- Устанавливаем переменную QtMsBuild ---
      - name: Set QtMsBuild path
        run: echo "QtMsBuild=$env:Qt5_Dir\msbuild" >> $env:GITHUB_ENV

      # --- Билдим Win32 ---
      - name: Build IPSharkk (Win32)
        run: msbuild IPSharkk.sln /p:Configuration=Release /p:Platform=Win32 /verbosity:minimal

      # --- Билдим x64 ---
      - name: Build IPSharkk (x64)
        run: msbuild IPSharkk.sln /p:Configuration=Release /p:Platform=x64 /verbosity=minimal

      # --- Выгружаем exe ---
      - name: Upload EXE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VPNClients
          path: |
            **/Win32/Release/*.exe
            **/x64/Release/*.exe
