name: Build VPN Clients (Win32)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt 5.15.2
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: win32_msvc2019

      - name: Add Qt bin to PATH (persist)
        run: |
          echo "QTDIR=$env:IQTA_TOOLS" >> $env:GITHUB_ENV
          echo "$env:IQTA_TOOLS\bin" >> $env:GITHUB_PATH
          setx PATH "$env:IQTA_TOOLS\bin;$env:PATH"

      - name: Verify Qt tools
        run: echo "Qt installed"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build IPSharkk (x86)
        run: msbuild IPSharkk.sln /p:Configuration=Release /p:Platform=Win32 /verbosity:minimal

      - name: Build TuxlerProxy (x86)
        run: msbuild TuxlerProxy.sln /p:Configuration=Release /p:Platform=Win32 /verbosity:minimal

      - name: Upload EXE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VPNClients
          path: |
            **/Release/*.exe
            **/x86/Release/*.exe
