name: Build VPN Clients (Win32)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt 5.15.2
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: win32_msvc2019
          tools: 'tools_qtcreator,qt5-msbuild'

      - name: Add Qt bin to PATH (persist)
        run: |
          echo "QTDIR=$env:Qt5_Dir" >> $env:GITHUB_ENV
          echo "$env:Qt5_Dir\bin" >> $env:GITHUB_PATH

      - name: Find Qt.props (debug)
        run: |
          echo "Searching for Qt.props..."
          dir $env:Qt5_Dir\..\..\..\Tools\QtMsBuild /s /b | findstr Qt.props || echo "Qt.props not found"

      - name: Set QtMsBuild env
        run: |
          $qtProps = Get-ChildItem -Path $env:Qt5_Dir\..\..\..\Tools\QtMsBuild -Recurse -Filter Qt.props | Select-Object -First 1
          if ($qtProps) {
            echo "QtMsBuild=$($qtProps.DirectoryName)" >> $env:GITHUB_ENV
          } else {
            echo "Qt.props not found, build may fail"
          }

      - name: Verify Qt tools
        run: qmake -v

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build IPSharkk (x86)
        run: msbuild IPSharkk.sln /p:Configuration=Release /p:Platform=Win32 /verbosity:minimal

      - name: Build TuxlerProxy (x86)
        run: msbuild TuxlerProxy.sln /p:Configuration=Release /p:Platform=Win32 /verbosity:minimal

      - name: Upload EXE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VPNClients
          path: |
            **/Release/*.exe
            **/x86/Release/*.exe
