name: Build VPN Clients (Win64)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt 5.15.2 (x64)
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: windows
          target: desktop
          arch: win64_msvc2019_64

      - name: Add Qt bin to PATH (persist)
        run: |
          echo "QTDIR=$env:Qt5_Dir" >> $env:GITHUB_ENV
          echo "$env:Qt5_Dir\bin" >> $env:GITHUB_PATH

      - name: Verify Qt tools
        run: qmake -v

      - name: Set QtMsBuild env
        run: echo "QtMsBuild=$env:Qt5_Dir\msbuild" >> $env:GITHUB_ENV

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build IPSharkk (x64)
        run: msbuild IPSharkk.sln /p:Configuration=Release /p:Platform=x64 /verbosity:minimal

      - name: Build TuxlerProxy (x64)
        run: msbuild TuxlerProxy.sln /p:Configuration=Release /p:Platform=x64 /verbosity:minimal

      - name: Upload EXE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VPNClients
          path: |
            **/Release/*.exe
            **/x64/Release/*.exe
