name: Build TuxlerVPN Simple

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild  
      uses: microsoft/setup-msbuild@v2
      
    - name: Install Qt 5.15
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop' 
        arch: 'win32_msvc2019'
        modules: 'qtwebengine qtmultimedia'
        
    - name: Create stub files for missing dependencies
      run: |
        # Создаем заглушки для отсутствующих файлов
        New-Item -ItemType Directory -Force -Path "1111111/winsparkle/include"
        echo "// WinSparkle stub" > "1111111/winsparkle/include/winsparkle.h"
        echo "" > "1111111/winsparkle/WinSparkle.lib"
        
        # Создаем минимальные заголовки если нужно
        if (!(Test-Path "1111111/version_info.h")) {
          echo '#define VER_FILEVERSION_STR "1.0.0"' > "1111111/version_info.h"
        }
      shell: powershell
      
    - name: Try to build
      continue-on-error: true
      run: |
        cd 1111111
        set QTDIR=${{ env.Qt5_Dir }}
        msbuild TuxlerProxy.vcxproj /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0
      shell: cmd
      
    - name: Upload any generated files
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-attempt
        path: |
          1111111/release/
          1111111/debug/
