jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          host: windows
          target: desktop
          arch: win32_msvc2019

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build IPSharkk (x86)
        run: msbuild IPSharkk.sln /p:Configuration=Release /p:Platform=Win32

      - name: Build TuxlerProxy (x86)
        run: msbuild TuxlerProxy.sln /p:Configuration=Release /p:Platform=Win32

      - name: Upload EXE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VPNClients
          path: |
            Release/*.exe
            x86/Release/*.exe
