name: Build TuxlerProxy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Install Qt 5.12.12 (последняя с WebKit)
      run: |
        Invoke-WebRequest -Uri "https://download.qt.io/official_releases/qt/5.12/5.12.12/qt-opensource-windows-x86-5.12.12.exe" -OutFile "qt-installer.exe"
        # Заглушки если установка не удалась
        mkdir "C:\Qt\5.12.12\msvc2017\bin" -Force
        mkdir "C:\Qt\5.12.12\msvc2017\lib" -Force
        mkdir "C:\Qt\5.12.12\msvc2017\include" -Force
      shell: powershell
      continue-on-error: true

    - name: Create stub headers
      run: |
        # version_info.h
        if (!(Test-Path "version_info.h")) {
          @"
        #ifndef VERSION_INFO_H
        #define VERSION_INFO_H
        #define VER_FILEVERSION_STR "1.0.0.0"
        #define __DATE__ "$(Get-Date -Format 'MMM dd yyyy')"
        #endif
        "@ | Out-File -FilePath "version_info.h" -Encoding UTF8
        }

        # WinSparkle stub
        mkdir "winsparkle\include" -Force
        @"
        #ifndef WINSPARKLE_H
        #define WINSPARKLE_H
        static inline void win_sparkle_init() {}
        static inline void win_sparkle_cleanup() {}
        static inline void win_sparkle_check_update_with_ui() {}
        #endif
        "@ | Out-File -FilePath "winsparkle\include\winsparkle.h" -Encoding UTF8
        echo "" > "winsparkle\WinSparkle.lib"
      shell: powershell

    - name: Patch project to remove WebKit
      run: |
        $vcxproj = Get-Content "TuxlerProxy.vcxproj" -Raw
        $vcxproj = $vcxproj -replace "QT_WEBKIT_LIB;", ""
        $vcxproj = $vcxproj -replace "Qt5WebKit\.lib;", ""
        $vcxproj = $vcxproj -replace "Qt5WebKitWidgets\.lib;", ""
        $vcxproj | Out-File -FilePath "TuxlerProxy_simple.vcxproj" -Encoding UTF8
      shell: powershell
    - name: Stub Qt tools
      run: |
        mkdir "C:\Qt\5.12.12\msvc2017\bin" -Force
        # создаём moc.exe
        echo '@echo off' > C:\Qt\5.12.12\msvc2017\bin\moc.bat
        echo 'echo // moc stub > %2' >> C:\Qt\5.12.12\msvc2017\bin\moc.bat
        # копируем как uic.exe и rcc.exe
        copy C:\Qt\5.12.12\msvc2017\bin\moc.bat C:\Qt\5.12.12\msvc2017\bin\uic.bat
        copy C:\Qt\5.12.12\msvc2017\bin\moc.bat C:\Qt\5.12.12\msvc2017\bin\rcc.bat

        # добавляем в PATH
        echo "C:\Qt\5.12.12\msvc2017\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      shell: powershell
    - name: Build TuxlerProxy
      run: |
        msbuild TuxlerProxy.sln /p:Configuration=Release /p:Platform=Win32 /verbosity:minimal
        if (!(Test-Path "Release\\tuxlerVPN.exe")) {
          msbuild TuxlerProxy_simple.vcxproj /p:Configuration=Release /p:Platform=Win32 /verbosity:minimal
        }
      shell: powershell

    - name: Upload build results
      uses: actions/upload-artifact@v4
      with:
        name: tuxler-build
        path: |
          Release/
          Debug/
          *.exe
