name: Build VPN Clients (Win32)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt 5.15.2
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: win32_msvc2019

      - name: Add Qt bin to PATH (persist)
        run: |
          echo "QTDIR=$env:Qt5_Dir" >> $env:GITHUB_ENV
          echo "$env:Qt5_Dir\bin" >> $env:GITHUB_PATH

      - name: Verify Qt install
        run: qmake -v

      - name: Download QtMsBuild
        run: |
          git clone --depth=1 https://github.com/qt-labs/vstools.git
          mkdir "$env:Qt5_Dir\msvc2019\msbuild"
          Copy-Item "vstools\QtMsBuild\*" "$env:Qt5_Dir\msvc2019\msbuild\" -Recurse -Force

      - name: Verify QtMsBuild
        run: dir "$env:Qt5_Dir\msvc2019\msbuild"

      - name: Set QtMsBuild env
        run: echo "QtMsBuild=$env:Qt5_Dir\msvc2019\msbuild" >> $env:GITHUB_ENV

      - name: Set QtMsBuild env
        run: echo "QtMsBuild=$env:Qt5_Dir\msbuild" >> $env:GITHUB_ENV

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build IPSharkk (x86)
        run: msbuild IPSharkk.sln /p:Configuration=Release /p:Platform=Win32 /verbosity:minimal

      - name: Upload EXE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VPNClients
          path: |
            **/Win32/Release/*.exe
